# Generated by Django 3.1.7 on 2022-01-31 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('Carrier_Id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=40)),
                ('Address', models.CharField(default='', max_length=150)),
                ('Mobile', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('Ditributor_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=150)),
                ('Mobile', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor_Group',
            fields=[
                ('Distributor_Group_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Distributor_Group_Name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('Farmer_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=150)),
                ('Mobile', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer_Group',
            fields=[
                ('Farmer_Group_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Farmer_Group_Name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(default='', max_length=20)),
                ('Product_Rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quality_Check', models.FloatField(default=1)),
                ('Carrier_Charges', models.FloatField(default=2.5)),
                ('Distributon_Chagres', models.FloatField(default=2.0)),
                ('Marketing_Charges', models.FloatField(default=1.0)),
                ('Other_Charges', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.CharField(default='Morning', max_length=20)),
                ('Quantity', models.IntegerField(default=0)),
                ('Rate', models.IntegerField(default=0)),
                ('Paid', models.IntegerField(default=0)),
                ('Due', models.IntegerField(default=0)),
                ('Farmer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.farmer')),
                ('Product_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.product')),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='Farmer_Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.farmer_group'),
        ),
        migrations.CreateModel(
            name='DistributorExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.CharField(default='Morning', max_length=20)),
                ('Quantity', models.IntegerField(default=0)),
                ('Rate', models.IntegerField(default=0)),
                ('Paid', models.IntegerField(default=0)),
                ('Due', models.IntegerField(default=0)),
                ('Distributor_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.distributor')),
                ('Product_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.product')),
            ],
        ),
        migrations.AddField(
            model_name='distributor',
            name='Group_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.distributor_group'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=150)),
                ('Mobile', models.IntegerField(default=0)),
                ('Distributor_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='CarrierExpenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.CharField(default='Morning', max_length=40)),
                ('Quantity', models.IntegerField(default=0)),
                ('Rate', models.IntegerField(default=0)),
                ('Paid', models.IntegerField(default=0)),
                ('Due', models.IntegerField(default=0)),
                ('isPaid', models.BooleanField(default=False)),
                ('Carrier_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.carrier')),
                ('Product_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.CharField(default='Morning', max_length=20)),
                ('Quantity', models.FloatField(default=0)),
                ('Rate', models.IntegerField(default=0)),
                ('Paid', models.IntegerField(default=0)),
                ('Due', models.IntegerField(default=0)),
                ('isPaid', models.BooleanField(default=False)),
                ('Customer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.customer')),
                ('Product_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.product')),
            ],
            options={
                'unique_together': {('Customer_Id', 'Date')},
            },
        ),
    ]
